'use client';
export function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; document.body.appendChild(a); a.click();
  a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1500);
}
export function downloadHtml(code, name = 'vibeui-design.html') {
  downloadBlob(new Blob([code], { type: 'text/html;charset=utf-8' }), name);
}
export function buildBrief(code, prompt = '') {
  const comps = Array.from(new Set((code.match(/data-component="([^"]+)"/g) || [])
    .map((m) => m.replace(/data-component="|"/g, ''))));
  const fonts = /font-(sans|serif|mono)/.test(code) ? 'Tailwind default stack (Inter / system-ui)' : 'system-ui, sans-serif';
  return `VIBEUI — PROJECT BRIEF
=========================================
Dibuat  : ${new Date().toLocaleString('id-ID')}
Prompt  : ${prompt || '(template pustaka)'}

1. RINGKASAN DESAIN
Halaman ini dibangun dengan pendekatan anti-slop: struktur bento grid,
whitespace lega (p-6 s/d p-12), sudut membulat penuh (rounded-2xl s/d rounded-full),
dan kontras teks tajam. Tanpa gradasi neon atau warna pelangi.

2. PANDUAN WARNA (MONOKROMATIK PREMIUM)
- Latar utama     : #000000 / zinc-950 (#09090b)
- Kartu & sidebar : zinc-900/50 + backdrop-blur
- Border          : zinc-800/60 (dark) — zinc-200 (light)
- Teks utama      : zinc-50   | Sub-teks: zinc-400
- Light mode      : bg-white / zinc-50, teks zinc-900, sub zinc-500

3. TIPOGRAFI
- Font family : ${fonts}
- Heading     : font-bold tracking-tight, leading ketat (1.05)
- Body        : text-sm/base leading-relaxed

4. DAFTAR KOMPONEN TERDETEKSI (${comps.length})
${comps.map((c, i) => ` ${String(i + 1).padStart(2, '0')}. ${c}`).join('\n') || ' (tidak ada label data-component)'}

5. CARA PAKAI
- Buka index.html langsung di browser (offline ready).
- Tailwind dimuat via CDN. Untuk produksi, compile Tailwind lokal.
- Setiap elemen punya data-component agar mudah diedit ulang di VibeUI.

6. LISENSI
Kode hasil generate bebas dipakai untuk proyek komersial klien Anda.
=========================================
Generated by VibeUI — vibeui.vercel.app`;
}
export function downloadBrief(code, prompt) {
  downloadBlob(new Blob([buildBrief(code, prompt)], { type: 'text/plain;charset=utf-8' }), 'PROJECT-BRIEF.txt');
}
export async function downloadZip(code, prompt = '') {
  const JSZip = (await import('jszip')).default;
  const zip = new JSZip();
  const root = zip.folder('vibeui-project');
  root.file('index.html', code);
  root.file('PROJECT-BRIEF.txt', buildBrief(code, prompt));
  root.file('README.md', `# VibeUI Export\n\nBuka \`index.html\` di browser.\n\n- Prompt: ${prompt || '-'}\n- Dibuat: ${new Date().toISOString()}\n`);
  root.folder('assets').file('.gitkeep', '');
  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
  downloadBlob(blob, 'vibeui-project.zip');
}
export async function copyCode(code) {
  try { await navigator.clipboard.writeText(code); return true; }
  catch {
    const ta = document.createElement('textarea');
    ta.value = code; document.body.appendChild(ta); ta.select();
    document.execCommand('copy'); ta.remove(); return true;
  }
}
